name: API Tests Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Запуск каждый день в 00:00 UTC
  workflow_dispatch:  # Возможность запустить вручную

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Firefox Dependencies
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-0 libx11-xcb1

      - name: Fetch browsers via Camoufox
        run: camoufox fetch

      - name: Run Tests
        env:
          HTTP_PROXY:  "http://${{ secrets.RUSSIAN_PROXY }}"
          HTTPS_PROXY: "http://${{ secrets.RUSSIAN_PROXY }}"
        run: pytest # --disable-warnings  # Без --snapshot-update