name: Generate and Deploy API Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Позволяет запускать этот workflow вручную из вкладки Actions
  workflow_dispatch:

# Разрешения для развертывания на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Настраиваем environment для GitHub Pages
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install json-schema-for-humans

      - name: Install the package in development mode
        run: |
          pip install -e .

      - name: Generate API documentation
        run: |
          # Очищаем директорию docs, сохраняя .gitkeep если он есть
          mkdir -p docs
          find docs -type f -not -name ".gitkeep" -delete
          
          # Генерируем документацию по схемам напрямую из __snapshots__
          python -m json_schema_for_humans.generate tests/__snapshots__/ docs --config-file json_schema_for_humans_config.json
          
          # Создаем индексную страницу
          python create_index_schema.py
          
          # Добавляем файл .nojekyll для корректной работы GitHub Pages
          touch docs/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs'

  # Отдельная задача для деплоя на GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
